-- AlgoAPI initial seed
-- Preconditions:
-- 1. algo_api database already exists.
-- 2. Spring Boot has been started once so JPA created the tables.
-- 3. algorithm, problems, problem_algorithms are empty.
-- 4. AUTO_INCREMENT starts at 1.

USE algoapi;
SET NAMES utf8mb4;

START TRANSACTION;

-- 1. algorithm (33 rows)
INSERT INTO algorithm (name) VALUES
    ('GREEDY'),
    ('SPARSE_ARRAY'),
    ('UNION_FIND'),
    ('DATA_STRUCTURE'),
    ('DIJKSTRA'),
    ('BINARY_SEARCH'),
    ('MONOTONIC_DEQUE'),
    ('ZERO_ONE_BFS'),
    ('TWO_POINTER'),
    ('BFS'),
    ('PRIORITY_QUEUE'),
    ('PREFIX_SUM'),
    ('DIFFERENCE_ARRAY'),
    ('DYNAMIC_PROGRAMMING'),
    ('GRAPH'),
    ('BITMASK'),
    ('STACK'),
    ('DFS'),
    ('TREE_DP'),
    ('TREE'),
    ('TOPOLOGICAL_SORT'),
    ('SORTING'),
    ('LINKED_LIST'),
    ('STRING'),
    ('MATH'),
    ('TRIE'),
    ('RECURSION'),
    ('COMBINATORICS'),
    ('LIS'),
    ('DEQUE'),
    ('SIMULATION'),
    ('SPFA'),
    ('DIVIDE_AND_CONQUER');

-- 2. problems (100 rows)
INSERT INTO problems (platform, number, title, level, url, created_at) VALUES
    ('LEETCODE', 2708, 'Maximum Strength of a Group', 'Medium', 'https://leetcode.com/problems/maximum-strength-of-a-group/description/', NOW()),
    ('PROGRAMMERS', NULL, '호텔 방 배정', 'Lv4', 'https://school.programmers.co.kr/learn/courses/30/lessons/64063/', NOW()),
    ('LEETCODE', 2007, 'Find Original Array From Doubled Array', 'Medium', 'https://leetcode.com/problems/find-original-array-from-doubled-array/description/', NOW()),
    ('LEETCODE', 1946, 'Largest Number After Mutating Substring', 'Medium', 'https://leetcode.com/problems/largest-number-after-mutating-substring/description/', NOW()),
    ('LEETCODE', 1353, 'Maximum Number of Events That Can Be Attended', 'Medium', 'https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/description/', NOW()),
    ('LEETCODE', 1631, 'Path With Minimum Effort', 'Medium', 'https://leetcode.com/problems/path-with-minimum-effort/description/', NOW()),
    ('LEETCODE', 540, 'Single Element in a Sorted Array', 'Medium', 'https://leetcode.com/problems/single-element-in-a-sorted-array/description/', NOW()),
    ('LEETCODE', 1499, 'Max Value of Equation', 'Medium', 'https://leetcode.com/problems/max-value-of-equation/description/', NOW()),
    ('PROGRAMMERS', NULL, 'GPS', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/1837/', NOW()),
    ('LEETCODE', 1438, 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit', 'Medium', 'https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/description/', NOW()),
    ('LEETCODE', 81, 'Search in Rotated Sorted Array II', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/', NOW()),
    ('LEETCODE', 33, 'Search in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/description/', NOW()),
    ('LEETCODE', 3108, 'Minimum Cost Walk in Weighted Graph', 'Hard', 'https://leetcode.com/problems/minimum-cost-walk-in-weighted-graph/description/', NOW()),
    ('PROGRAMMERS', NULL, '아이템 줍기', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/87694', NOW()),
    ('LEETCODE', 2406, 'Divide Intervals Into Minimum Number of Groups', 'Medium', 'https://leetcode.com/problems/divide-intervals-into-minimum-number-of-groups/description/', NOW()),
    ('SWEA', 4052, '프리랜서', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWItDD5qAdkDFAWQ', NOW()),
    ('LEETCODE', 3286, 'Find a Safe Walk Through a Grid', 'Medium', 'https://leetcode.com/problems/find-a-safe-walk-through-a-grid/description/', NOW()),
    ('LEETCODE', 1368, 'Minimum Cost to Make at Least One Valid Path in a Grid', 'Hard', 'https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/description/', NOW()),
    ('LEETCODE', 864, 'Shortest Path to Get All Keys', 'Hard', 'https://leetcode.com/problems/shortest-path-to-get-all-keys/description/', NOW()),
    ('LEETCODE', 847, 'Shortest Path Visiting All Nodes', 'Hard', 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/description/', NOW()),
    ('PROGRAMMERS', NULL, '미로 탈출 명령어', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/150365', NOW()),
    ('LEETCODE', 309, 'Best Time to Buy and Sell Stock with Cooldown', 'medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/description/', NOW()),
    ('LEETCODE', 494, 'Target Sum', 'medium', 'https://leetcode.com/problems/target-sum/description/', NOW()),
    ('LEETCODE', 85, 'Maximal Rectangle', 'hard', 'https://leetcode.com/problems/maximal-rectangle/description/', NOW()),
    ('PROGRAMMERS', NULL, '동굴 탐험', 'Lv4', 'https://school.programmers.co.kr/learn/courses/30/lessons/67260', NOW()),
    ('PROGRAMMERS', NULL, '양과 늑대', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/92343', NOW()),
    ('LEETCODE', 42, 'Trapping Rain Water', 'hard', 'https://leetcode.com/problems/trapping-rain-water/description/', NOW()),
    ('LEETCODE', 2246, 'Longest Path With Different Adjacent Characters', 'hard', 'https://leetcode.com/problems/longest-path-with-different-adjacent-characters/description/', NOW()),
    ('LEETCODE', 624, 'Maximum Distance in Arrays', 'Medium', 'https://leetcode.com/problems/maximum-distance-in-arrays/description/', NOW()),
    ('LEETCODE', 63, 'Unique Paths II', 'Medium', 'https://leetcode.com/problems/unique-paths-ii/description/', NOW()),
    ('LEETCODE', 310, 'Minimum Height Trees', 'Medium', 'https://leetcode.com/problems/minimum-height-trees/description/', NOW()),
    ('LEETCODE', 238, 'Product of Array Except Self', 'Medium', 'https://leetcode.com/problems/product-of-array-except-self/description/', NOW()),
    ('LEETCODE', 684, 'Redundant Connection', 'Medium', 'https://leetcode.com/problems/redundant-connection/description/', NOW()),
    ('LEETCODE', 630, 'Course Schedule III', 'Hard', 'https://leetcode.com/problems/course-schedule-iii/description/', NOW()),
    ('PROGRAMMERS', NULL, '쿠기 구입', 'Lv4', 'https://school.programmers.co.kr/learn/courses/30/lessons/49995', NOW()),
    ('LEETCODE', 547, 'Number of Provinces', 'Medium', 'https://leetcode.com/problems/number-of-provinces/description/', NOW()),
    ('LEETCODE', 128, 'Longest Consecutive Sequence', 'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/description/', NOW()),
    ('LEETCODE', 209, 'Minimum Size Subarray Sum', 'Medium', 'https://leetcode.com/problems/minimum-size-subarray-sum/description/', NOW()),
    ('LEETCODE', 210, 'Course Schedule II', 'Medium', 'https://leetcode.com/problems/course-schedule-ii/description/', NOW()),
    ('LEETCODE', 207, 'Course Schedule', 'Medium', 'https://leetcode.com/problems/course-schedule/description/', NOW()),
    ('LEETCODE', 45, 'Jump Game II', 'Medium', 'https://leetcode.com/problems/jump-game-ii/description/', NOW()),
    ('LEETCODE', 3584, 'Maximum Product of First and Last Elements of a Subsequence', 'Medium', 'https://leetcode.com/problems/maximum-product-of-first-and-last-elements-of-a-subsequence/description/', NOW()),
    ('LEETCODE', 2920, 'Maximum Points After Collecting Coins From All Nodes', 'Hard', 'https://leetcode.com/problems/maximum-points-after-collecting-coins-from-all-nodes/description/', NOW()),
    ('LEETCODE', 6, 'Zigzag Conversion', 'Medium', 'https://leetcode.com/problems/zigzag-conversion/description/', NOW()),
    ('SWEA', 5678, '팰린드롬', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRrK7KhO4DFAUo', NOW()),
    ('SWEA', 4050, '재관이의 대량 할인', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=4&contestProbId=AWIseXoKEUcDFAWN', NOW()),
    ('SWEA', 4261, '빠른 휴대전화 키패드', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWLL7kaaAPsDFAUW', NOW()),
    ('SWEA', 8934, '팰린드롬 공포증', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AW5jJcZ68LsDFATQ', NOW()),
    ('SWEA', 4301, '콩 많이 심기', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWLv-yZah48DFAVV', NOW()),
    ('SWEA', 7699, '수지의 수지 맞는 여행', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWqUzj0arpkDFARG', NOW()),
    ('PROGRAMMERS', NULL, '표 편집', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/81303', NOW()),
    ('SWEA', 7396, '종구의 딸이름 짓기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWm8hNu6llcDFASj', NOW()),
    ('SWEA', 8558, '동현이의 망한 옷가게', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AW1Bu6Lq2iwDFARC', NOW()),
    ('SWEA', 8383, '숫자 선물', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWyNS6oqhJkDFAVP', NOW()),
    ('SWEA', 9780, '외계인 침공', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXE0gpIa3dADFAVX', NOW()),
    ('SWEA', 13433, '격자 위의 가장 긴 경로', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AX4EOkz68NIDFARe', NOW()),
    ('SWEA', 4616, '점프점프! 개굴이의 점핑!', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWQmBXYq8zgDFAXj', NOW()),
    ('SWEA', 1231, '중위순회', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV140YnqAIECFAYD&', NOW()),
    ('SWEA', 10806, '수 만들기', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXTC4piqD_IDFASe', NOW()),
    ('SWEA', 3410, '동서양의 경계', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWEbScy6yS8DFAWs', NOW()),
    ('SWEA', 5949, '문자열 변경하기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWZ2JT2aC1MDFAUQ', NOW()),
    ('SWEA', 7812, '옥희의 OK! 부동산', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWslJ57qFS0DFASy', NOW()),
    ('SWEA', 1265, '달란트2', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV18R8FKIvoCFAZN', NOW()),
    ('SWEA', 1256, 'K번째 접미어', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV18GHd6IskCFAZN', NOW()),
    ('SWEA', 10202, '문자열 동화', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXMCa8EaVioDFAWv', NOW()),
    ('SWEA', 10204, '초밥 식사', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXMCcO16Vi8DFAWv', NOW()),
    ('SWEA', 11593, '애너그램 랭킹', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXfRiB5KKW8DFAS5', NOW()),
    ('SWEA', 8191, '만화책 정렬하기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWwtYmX6hvsDFAWU', NOW()),
    ('SWEA', 6809, '에너지 전송 순서', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWgv8zHKHbsDFAW0', NOW()),
    ('SWEA', 19118, '언덕길', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AYxCewMqiqwDFASu', NOW()),
    ('SWEA', 9325, '백화점', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AW-hfS2qgA0DFAVg', NOW()),
    ('SWEA', 25838, '여우 줄이기', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AZtxnSyquD7HBIQE', NOW()),
    ('SWEA', 10033, '카드 뒤집기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXJZ8ua6CTkDFAU3', NOW()),
    ('SWEA', 1259, '금속막대', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV18NaZqIt8CFAZN', NOW()),
    ('SWEA', 4534, '트리 흑백 색칠', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWO6esOKOKQDFAWw', NOW()),
    ('PROGRAMMERS', NULL, '보행자 천국', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/1832', NOW()),
    ('SWEA', 5521, '상원이의 생일파티', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWWO3kT6F2oDFAV4', NOW()),
    ('SWEA', 5357, '터널 속의 기차', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWVWh6zasSkDFAUO', NOW()),
    ('SWEA', 7534, '스택 장인', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWopE0K61xADFARx', NOW()),
    ('SWEA', 7991, '줄 세우기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWvQdg1KU3QDFASy', NOW()),
    ('SWEA', 3503, '초보자를 위한 점프대 배치하기', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWGsV8IaAXsDFAVW', NOW()),
    ('SWEA', 10037, '트리 복구', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXJZ-XXKCb0DFAU3', NOW()),
    ('PROGRAMMERS', NULL, '등대', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/133500', NOW()),
    ('PROGRAMMERS', NULL, '코딩 테스트 공부', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/118668', NOW()),
    ('SWEA', 26390, '트리 바꾸기', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AZyNVrgKAVXHBIRj', NOW()),
    ('PROGRAMMERS', NULL, '행렬과 연산', 'Lv4', 'https://school.programmers.co.kr/learn/courses/30/lessons/118670', NOW()),
    ('PROGRAMMERS', NULL, '가장 긴 팰린드롬', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/12904', NOW()),
    ('SWEA', 1795, '인수의 생일 파티', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV4xuqCqBeUDFAUx', NOW()),
    ('PROGRAMMERS', NULL, '풍선 터트리기', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/68646', NOW()),
    ('SWEA', 3135, '홍준이의 사전 놀이', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV_6pTXqsXUDFAWS', NOW()),
    ('SWEA', 3289, '서로소 집합', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWBJKA6qr2oDFAWr', NOW()),
    ('LEETCODE', 105, 'Construct Binary Tree from Preorder and Inorder Traversal', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/', NOW()),
    ('PROGRAMMERS', NULL, '카드 짝 맞추기', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/72415?language=java', NOW()),
    ('PROGRAMMERS', NULL, '표현 가능한 이진 트리', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/150367?language=cpp#', NOW()),
    ('SWEA', 1849, '영준이의 무게 측정', 'D6', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5LeQJqDpwDFAXc', NOW()),
    ('SWEA', 10507, '영어 공부', 'D5', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXNQOb3avD0DFAXS', NOW()),
    ('LEETCODE', 21, 'Merge Two Sorted Lists', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/description/', NOW()),
    ('PROGRAMMERS', NULL, '경주로 건설', 'Lv3', 'https://school.programmers.co.kr/learn/courses/30/lessons/67259', NOW()),
    ('SWEA', 19004, '점프 놀이', 'D4', 'https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AYtrEOraDk0DFAR-', NOW()),
    ('LEETCODE', 2931, 'Maximum Spending After Buying Items', 'Hard', 'https://leetcode.com/problems/maximum-spending-after-buying-items/description/', NOW());

-- 3. problem_algorithms (174 rows)
INSERT INTO problem_algorithms (problem_id, algo_id) VALUES
    (1, 1),
    (2, 2),
    (2, 3),
    (2, 4),
    (3, 1),
    (4, 1),
    (5, 3),
    (6, 5),
    (7, 6),
    (8, 7),
    (9, 5),
    (9, 8),
    (10, 9),
    (10, 7),
    (11, 6),
    (12, 6),
    (13, 3),
    (14, 10),
    (15, 11),
    (15, 12),
    (15, 13),
    (16, 14),
    (17, 15),
    (17, 8),
    (18, 15),
    (18, 8),
    (18, 5),
    (19, 15),
    (19, 16),
    (20, 15),
    (20, 16),
    (21, 15),
    (21, 1),
    (22, 14),
    (23, 14),
    (24, 17),
    (24, 14),
    (25, 10),
    (25, 4),
    (26, 18),
    (26, 16),
    (27, 4),
    (27, 17),
    (28, 19),
    (28, 18),
    (29, 1),
    (30, 14),
    (31, 20),
    (31, 21),
    (32, 12),
    (32, 1),
    (33, 15),
    (33, 20),
    (33, 3),
    (34, 22),
    (34, 1),
    (34, 11),
    (35, 12),
    (35, 6),
    (35, 9),
    (36, 15),
    (36, 3),
    (37, 4),
    (37, 3),
    (38, 9),
    (38, 12),
    (39, 15),
    (39, 21),
    (40, 15),
    (40, 21),
    (41, 14),
    (41, 1),
    (42, 14),
    (42, 9),
    (43, 20),
    (43, 18),
    (43, 23),
    (43, 14),
    (44, 24),
    (44, 25),
    (45, 14),
    (46, 1),
    (47, 26),
    (48, 1),
    (48, 25),
    (49, 1),
    (49, 25),
    (50, 18),
    (51, 23),
    (51, 17),
    (52, 10),
    (53, 1),
    (54, 1),
    (55, 14),
    (56, 14),
    (57, 14),
    (57, 22),
    (58, 27),
    (58, 20),
    (59, 27),
    (60, 1),
    (60, 12),
    (61, 1),
    (62, 9),
    (63, 25),
    (63, 1),
    (64, 22),
    (64, 24),
    (64, 26),
    (65, 24),
    (65, 1),
    (66, 22),
    (66, 1),
    (67, 25),
    (67, 28),
    (68, 22),
    (68, 1),
    (69, 14),
    (70, 29),
    (70, 6),
    (70, 14),
    (71, 4),
    (71, 30),
    (71, 9),
    (71, 12),
    (72, 4),
    (72, 17),
    (73, 1),
    (73, 25),
    (74, 4),
    (75, 20),
    (75, 19),
    (76, 14),
    (77, 15),
    (77, 10),
    (78, 9),
    (78, 31),
    (79, 17),
    (80, 1),
    (80, 25),
    (81, 1),
    (81, 22),
    (82, 20),
    (82, 21),
    (83, 20),
    (83, 19),
    (83, 10),
    (83, 18),
    (84, 14),
    (84, 5),
    (85, 20),
    (86, 4),
    (86, 30),
    (87, 14),
    (88, 5),
    (88, 32),
    (89, 17),
    (90, 26),
    (91, 3),
    (92, 20),
    (92, 33),
    (92, 27),
    (93, 31),
    (93, 18),
    (93, 10),
    (94, 33),
    (94, 16),
    (95, 3),
    (96, 9),
    (97, 23),
    (98, 5),
    (99, 14),
    (99, 18),
    (100, 1);

COMMIT;

-- Verify
SELECT * FROM algorithm;
SELECT * FROM problems;
SELECT * FROM problem_algorithms;
